apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cpanel-nocnexus-com-cert
  namespace: default  # Match the namespace of the Ingress
spec:
  secretName: cpanel-nocnexus-com-tls  # Secret to store the certificate
  dnsNames:
  - cpanel.nocnexus.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  duration: 2160h  # 90 days
  renewBefore: 360h  # Renew 15 days before expiry
