apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-hello-world-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    cert-manager.io/cluster-issuer: letsencrypt-prod  # Optional: for auto-certificate management
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Optional: force HTTP to HTTPS
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - cpanel.nocnexus.com
    secretName: cpanel-nocnexus-com-tls
  rules:
  - host: cpanel.nocnexus.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodejs-hello-world
            port:
              number: 3000
